[package]
org = "ballerinax"
name = "mysql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../mysql-native/build/libs/mysql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mysql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.21.jar"
artifactId = "mysql-connector-java"
groupId = "mysql"
scope = "testOnly"
version = "8.0.17"
