[project]
org-name = "ballerinax"
version = "@toml.version@"

[dependencies]
"ballerina/sql" = "@stdlib.sql.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "mysql-native"
    version = "@project.version@"
    path = "../mysql-native/build/libs/mysql-native-@project.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["mysql"]

    [[platform.libraries]]
    artifactId = "ballerina-sql"
    version = "@stdlib.sql.native.version@"
    path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["mysql"]

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "./lib/mysql-connector-java-8.0.21.jar"
    groupId = "mysql"
    modules = ["mysql"]
    scope = "testOnly"
    
