[package]
org = "ballerinax"
name = "mysql"
version = "@toml.version@"
[[dependency]]
org = "ballerina"
name = "sql"
version = "@stdlib.sql.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[platform.java11.dependency]]
path = "../mysql-native/build/libs/mysql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mysql-native"
version = "@project.version@"


[[platform.java11.dependency]]
path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-sql"
version = "@stdlib.sql.native.version@"


[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.21.jar"
artafactId = "mysql-connector-java"
groupId = "mysql"
scope = "testOnly"
version = "8.0.17"
