[project]
org-name = "ballerinax"
version = "@toml.version@"

[dependencies]
"ballerina/sql" = "@stdlib.sql.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/filepath" = "@stdlib.filepath.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/math" = "@stdlib.math.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/lang.transaction" = "@stdlib.transaction.version@"
"ballerina/task" = "@stdlib.task.version@"
"ballerina/file" = "@stdlib.file.version@"
"ballerina/reflect" = "@stdlib.reflect.version@"
"ballerina/mime" = "@stdlib.mime.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/auth" = "@stdlib.auth.version@"
"ballerina/http" = "@stdlib.http.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "mysql-native"
    version = "@project.version@"
    path = "../mysql-native/build/libs/mysql-native-@project.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["mysql"]

    [[platform.libraries]]
    artifactId = "ballerina-sql"
    version = "@stdlib.sql.native.version@"
    path = "@project.path@/bre/lib/sql-native-@stdlib.sql.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["mysql"]

    [[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "8.0.17"
    path = "./lib/mysql-connector-java-8.0.21.jar"
    groupId = "mysql"
    modules = ["mysql"]
    scope = "testOnly"
    
