[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql"
    version = "@project.version@"
    path = "../mysql-native/build/libs/mysql-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["mysql"]

    [[platform.libraries]]
    artifactId = "sql"
    version = "0.5.0"
    path = "@project.path@/bre/lib/ballerina-sql-0.5.0-java.jar"
    groupId = "ballerina"
    modules = ["mysql"]
