[package]
org = "ballerinax"
name = "mysql"
version = "1.5.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mysql-native"
version = "1.5.1"
path = "../native/build/libs/mysql-native-1.5.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.5.1"
path = "./lib/sql-native-1.5.1-20221004-155400-eed6d7f.jar"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.29.jar"
scope = "testOnly"
