[package]
org = "ballerinax"
name = "mysql"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/mysql-native-1.3.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.3.0-20211221-080400-54b27f2.jar"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.21.jar"
scope = "testOnly"
