[package]
org = "ballerinax"
name = "mysql"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/mysql-native-1.0.2-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.1-20211115-134300-f6e820e.jar"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.21.jar"
scope = "testOnly"
