[package]
org = "ballerinax"
name = "mysql"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/mysql-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0-20211008-021900-95abc84.jar"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.21.jar"
scope = "testOnly"
