[package]
org = "ballerinax"
name = "mysql"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/mysql-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mysql-native"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/sql-native-@sql.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "sql-native"
version = "@sql.native.version@"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-@mysql.driver.version@.jar"
artifactId = "mysql-connector-java"
groupId = "mysql"
scope = "testOnly"
version = "@mysql.driver.version@"
